/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Lenovo
 */
public class Vista_Materia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Materia
     */
    public Vista_Materia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTtablaMateria = new javax.swing.JTable();
        jBinsertar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jBbajaLogica = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(570, 300));

        jTtablaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Materia", "Nombre Materia"
            }
        ));
        jScrollPane1.setViewportView(jTtablaMateria);

        jBinsertar.setText("Insertar");

        jBactualizar.setText("Actualizar");

        jBborrar.setText("Borrar");

        jBbajaLogica.setText("Baja/Alta Logica");
        jBbajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaLogicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBinsertar)
                        .addGap(59, 59, 59)
                        .addComponent(jBactualizar)
                        .addGap(38, 38, 38)
                        .addComponent(jBborrar)
                        .addGap(53, 53, 53)
                        .addComponent(jBbajaLogica)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinsertar)
                    .addComponent(jBactualizar)
                    .addComponent(jBborrar)
                    .addComponent(jBbajaLogica))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBbajaLogicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBbajaLogica;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBinsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTtablaMateria;
    // End of variables declaration//GEN-END:variables
}
