/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexion.conexion;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import persistencia.AlumnoData;

/**
 *
 * @author Lenovo
 */
public class Vista_transversal extends javax.swing.JFrame {
    
    conexion conexion = new conexion();
    AlumnoData alumnoData = new AlumnoData(conexion);
    List<Alumno> alumnos = alumnoData.obtenerAlumnos();
    public static DefaultTableModel modelo = new DefaultTableModel();
   
    public Vista_transversal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMalumno = new javax.swing.JMenu();
        jMCargaAlumno = new javax.swing.JMenuItem();
        jMmateria = new javax.swing.JMenu();
        jMCargaMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jMalumno.setText("Alumno");
        jMalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumnoActionPerformed(evt);
            }
        });

        jMCargaAlumno.setText("Carga Alumnos");
        jMCargaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCargaAlumnoActionPerformed(evt);
            }
        });
        jMalumno.add(jMCargaAlumno);

        jMenuBar1.add(jMalumno);

        jMmateria.setText("Materia");

        jMCargaMateria.setText("Carga Materias");
        jMCargaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCargaMateriaActionPerformed(evt);
            }
        });
        jMmateria.add(jMCargaMateria);

        jMenuBar1.add(jMmateria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMalumnoActionPerformed

    private void jMCargaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCargaAlumnoActionPerformed
        Vista_Alumno vistaalumno = new Vista_Alumno ();
            escritorio.add(vistaalumno);
            vistaalumno.setVisible(true);
    }//GEN-LAST:event_jMCargaAlumnoActionPerformed

    private void jMCargaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCargaMateriaActionPerformed
            Vista_Materia vistamateria = new Vista_Materia ();
            escritorio.add(vistamateria);
            vistamateria.setVisible(true);
    }//GEN-LAST:event_jMCargaMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_transversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_transversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_transversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_transversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_transversal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMCargaAlumno;
    private javax.swing.JMenuItem jMCargaMateria;
    private javax.swing.JMenu jMalumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMmateria;
    // End of variables declaration//GEN-END:variables



}
